### ISSUE TITLE
Default settings in a JSON

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/smartads-app-extension-worona#1]
The first version of the extension will directly generate a .json with the description of the ads. In order to generate the JSON we need:

- Number of positions in **home**.
- Number of positions in **post**. 
- For every position:
  - site_id
  - page_id
  - format_id
  - target
  - width 
  - height

`
{
  "home": {
    "pwa": [
      {"site_id":"sssss","page_id":"pppp","format_id":"ffff","target":"t=TT","width":"w","height":"h"}
      ]
  },
  "post": {
    "pwa": [{"site_id":"sssss","page_id":"pppp","format_id":"ffff","target":"t=TT","width":"w","height":"h"}],
    "amp": [{"site_id":"sssss","page_id":"pppp","format_id":"ffff","target":"t=TT","width":"w","height":"h"}]
  }
}
`

**Comment by luisherranz** [comment]
Let's call it home instead of post_list so it's consistent with the rest of the naming.

**Comment by Poliuk** [comment]
@luisherranz perfect. I've just updated the description. I guess that in the future we could have home / categories / tags

**Comment by Poliuk** [comment]
We have changed the algorithm that inserts ads, the JSON has to be consistent with it: https://github.com/worona/saturn-app-theme-worona/issues/60

**Comment by orballo** [comment]
Already done inside the theme.

We will move it to an independent package here https://github.com/worona/saturn-app-theme-worona/issues/119
