### ISSUE TITLE
Inject smartads scripts

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/smartads-app-extension-worona#2]
- https://support.smartadserver.com/s/article/ka00Y000000YuXSQA0/Tagging-guide
- https://support.smartadserver.com/s/article/ka00Y000000YsFVQA0/Exporting-ad-tags-Publisher-solution

**Comment by orballo** [comment]
Already done inside saturn. 

We will move it to an independent package here https://github.com/worona/saturn-app-theme-worona/issues/119
