### ISSUE TITLE
Insert the adds in post & post-list

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/smartads-app-extension-worona#3]
- This extension will include the ad-tags following the advertising map. 
- The "Ad component" should be able to render regular tags and <amp-ad> tags.

> **Related issue:** https://github.com/worona/saturn-app-theme-worona/issues/60

**Comment by Poliuk** [comment]
Once https://github.com/worona/saturn-app-theme-worona/issues/60 is working we will have to discuss which parts of the injector will be included in the theme and which ones can be part of the adds - extension.

**Comment by Poliuk** [comment]
After the release we will isolate this from the theme.

**Comment by orballo** [comment]
Closing this issue.

We will keep track of the independent packages here https://github.com/worona/saturn-app-theme-worona/issues/119
